services:

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  users-service:
    build: ./backend/users-service
    container_name: users-service
    ports:
      - "8081:8081"
    depends_on:
      - mongo

  orders-service:
    build: ./backend/orders-service
    container_name: orders-service
    ports:
      - "8082:8082"

  payments-service:
    build: ./backend/payments-service
    container_name: payments-service
    ports:
      - "8083:8083"

volumes:
  mongo_data:
